# base_config.yaml

# Simulation parameters
simulation:
  epochs: 50
  evaluate_every: 1
  batch_size: 15
  full_retrain: True
  kl_budget: 3.5

exp_name: "36nd_15_varprel_starc"
seed: 9

train_dataset:
  class: RandomNonDetTrajectoryDataset

eval_dataset:
  class: Random36NonDetTrajectoryDataset

# Model parameters
pref_model:
  class: EnsembleNonDetPreferenceModel
  model:
    input_size: 76
    layers: "[20, 5]"
    init_func: "xavier_uniform"
    activation_fn: "tanh"
  lr: 0.01
  train_test_split: 0.2
  train_batch_size: 50
  eval_batch_size: 1000
  num_epochs: 1000
  early_stopping_patience: 50
  early_stopping: True
  ensemble_size: 10
  standardize_features: True

reward_standardizer: 
  class: StarcNonDetRewardStandardizer
  dynamic_magnitude: True
  

# Data parameters
data:
  train_size: 15000
  test_size: 3000

# Trainer parameters
trainer: 
  class: BoltzmannBoNPolicyTrainer

# Data Selection Parameters
data_selection:
  policy: VarPSelectionPolicy

mdp:
  class: LavaPathNonDetMDP
  flip_preferences_prob: 0