# base_config.yaml

# Simulation parameters
simulation:
  epochs: 1
  evaluate_every: 1
  batch_size: 500
  full_retrain: True
  kl_budget: 3.5

exp_name: "base_exp"
seed: 9

train_dataset:
  class: RandomTrajectoryDataset

eval_dataset:
  class: CompleteTrajectoryDataset

# Model parameters
pref_model:
  class: EnsemblePreferenceModel
  model:
    input_size: 40
    layers: "[10,5]"
    init_func: "xavier_uniform"
    activation_fn: "tanh"
  lr: 0.01
  train_test_split: 0.2
  train_batch_size: 100
  eval_batch_size: 1000
  num_epochs: 1000
  early_stopping_patience: 50
  early_stopping: True
  ensemble_size: 20
  standardize_features: True
  set_reward_magnitude: 8000

reward_standardizer: 
  class: NoneRewardStandardizer
  dynamic_magnitude: False
  set_reward_magnitude: False
  mag: 1

# Data parameters
data:
  train_size: 3000
  test_size: 3000

# Trainer parameters
trainer: 
  class: BoltzmannBoNPolicyTrainer

# Data Selection Parameters
data_selection:
  policy: RandomSelectionPolicy

mdp:
  class: LavaPathDetMDP
  flip_preferences_prob: 0