# base_config.yaml

# Simulation parameters
simulation:
  epochs: 10
  batch_size: 10
  full_retrain: True
  kl_budget: 3.5

exp_name: "exp_none"
seed: 9

train_dataset:
  class: ExpBiasedTrajectoryDataset

eval_dataset:
  class: RandomTrajectoryDataset

# Model parameters
pref_model:
  class: EnsemblePreferenceModel
  model:
    input_size: 40
    layers: "[10, 5]"
    init_func: "xavier_uniform"
    activation_fn: "tanh"
  lr: 0.01
  train_test_split: 0.2
  train_batch_size: 10
  eval_batch_size: 1000
  num_epochs: 1000
  early_stopping_patience: 50
  early_stopping: True
  ensemble_size: 10
  standardize_features: True

reward_standardizer: 
  class: NoneRewardStandardizer

# Data parameters
data:
  train_size: 1000
  test_size: 1000

# Trainer parameters
trainer: 
  class: BoNPolicyTrainer

# Data Selection Parameters
data_selection:
  policy: RandomSelectionPolicy