name: act-pm
channels:
  - conda-forge
  - defaults
  - pytorch
  - conda
dependencies:
  - python=3.9
  - pip=23.3
  - pip:  
    - torch==2.2.2
    - torchvision==0.17.2
    - torchaudio==2.2.2
    - accelerate==0.33.0
    - datasets==2.21.0
    - evaluate==0.4.2
    - huggingface-hub==0.24.6
    - tokenizers==0.19.0
    - tqdm==4.66.3
    - transformers==4.44.2
    - peft==0.12.0
    - bitsandbytes==0.43.3
    - scipy==1.11.3
    - scikit-learn==1.3.2
    - trl==0.9.6
    - wandb==0.15.12
    - jupyter
    - sentencepiece==0.1.99
    - seaborn==0.13.2
    - GPUtil==1.4.0
